name: FeatherKeepInventory
version: '${project.version}'
main: dev.zerek.featherkeepinventory.FeatherKeepInventory
api-version: 1.21
depend: [ LuckPerms ]
authors: [ Zerek ]
description: Adds effects to players when they first join
permissions:
  feather.keepinventory.keep:
    default: false
  feather.keepinventory.staff:
    default: op